services:
  test:
    build: .
    volumes:
      - .:/sunray
    working_dir: /sunray/linux
    command: >
      bash -c "make build && make test"

  dev:
    build: .
    volumes:
      - .:/sunray
    working_dir: /sunray
    stdin_open: true
    tty: true
    entrypoint: bash
